package com.dulcerefugio.app.entunombre.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dulcerefugio.app.entunombre.data.dao.YoutubeVideo;
import com.dulcerefugio.app.entunombre.data.dao.GeneratedImages;

import com.dulcerefugio.app.entunombre.data.dao.YoutubeVideoDao;
import com.dulcerefugio.app.entunombre.data.dao.GeneratedImagesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig youtubeVideoDaoConfig;
    private final DaoConfig generatedImagesDaoConfig;

    private final YoutubeVideoDao youtubeVideoDao;
    private final GeneratedImagesDao generatedImagesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        youtubeVideoDaoConfig = daoConfigMap.get(YoutubeVideoDao.class).clone();
        youtubeVideoDaoConfig.initIdentityScope(type);

        generatedImagesDaoConfig = daoConfigMap.get(GeneratedImagesDao.class).clone();
        generatedImagesDaoConfig.initIdentityScope(type);

        youtubeVideoDao = new YoutubeVideoDao(youtubeVideoDaoConfig, this);
        generatedImagesDao = new GeneratedImagesDao(generatedImagesDaoConfig, this);

        registerDao(YoutubeVideo.class, youtubeVideoDao);
        registerDao(GeneratedImages.class, generatedImagesDao);
    }
    
    public void clear() {
        youtubeVideoDaoConfig.getIdentityScope().clear();
        generatedImagesDaoConfig.getIdentityScope().clear();
    }

    public YoutubeVideoDao getYoutubeVideoDao() {
        return youtubeVideoDao;
    }

    public GeneratedImagesDao getGeneratedImagesDao() {
        return generatedImagesDao;
    }

}
