package com.dulcerefugio.app.etn.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table generated_images.
 */
public class GeneratedImages {

    private Long id;
    private String path;
    private String date;

    public GeneratedImages() {
    }

    public GeneratedImages(Long id) {
        this.id = id;
    }

    public GeneratedImages(Long id, String path, String date) {
        this.id = id;
        this.path = path;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
