package com.dulcerefugio.app.etn.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table youtube_videos.
 */
public class YoutubeVideo {

    private String video_id;
    private String title;
    private String description;
    private String thumbnail_url;
    private java.util.Date created_at;

    public YoutubeVideo() {
    }

    public YoutubeVideo(String video_id) {
        this.video_id = video_id;
    }

    public YoutubeVideo(String video_id, String title, String description, String thumbnail_url, java.util.Date created_at) {
        this.video_id = video_id;
        this.title = title;
        this.description = description;
        this.thumbnail_url = thumbnail_url;
        this.created_at = created_at;
    }

    public String getVideo_id() {
        return video_id;
    }

    public void setVideo_id(String video_id) {
        this.video_id = video_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getThumbnail_url() {
        return thumbnail_url;
    }

    public void setThumbnail_url(String thumbnail_url) {
        this.thumbnail_url = thumbnail_url;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

}
